### ISSUE TITLE
Feature request: move points with mouse drag

### ISSUE THREAD

**Issue by jankaWIS** [ddowd97/Python-Image-Morpher#6]
The GUI is great and I still can't stop admiring it. I was wondering -- would it be possible to add a functionality that a point can be selected after it's placed and then with a drag moved to another location? Because now if one makes a mistake or is not precise enough, the only fix is to delete the point and then place it again which is a bit annoying. And even more if one realises that this mistake has been done a few moves back :). 

And especially with the automatic feature recognition mentioned in https://github.com/ddowd97/Python-Image-Morpher/issues/2, that would be a killer ;). I have some code related to automatic face landmark detection which I can share, it's not working great by itself but if the user could then tweak the not fitting parts, it would save the user a lot of time.

**Comment by ddowd97** [comment]
Just as an update, I now have a working prototype for this request that I think is turning out quite nicely. :) There's still much to iron out with this as well as the slew of other features coming in the next update, so no ETA for the next stable release yet... I didn't believe in feature creep until now. Sheesh, it's very real.

<p align="center">
  <img src="https://media4.giphy.com/media/WTnYG4TVJeSAfrnAJk/giphy.gif?cid=790b76114ff102df2d5c4a92ad4a11133021a6c597271218&rid=giphy.gif&ct=g"><br>
</p>

_Note that my capture software seems to have offset my cursor to the right by a bit, but PIM would accept that input as well._

**Comment by jankaWIS** [comment]
Wow, that looks great! And all the triangulation is nicely working out, that is really good. Does it work on both images (left and right)? Have you tried how it looks if you morph it? I mean for sure in this case you are going to have a lot of artefacts because the triangles do not correspond nicely but for some point on the back or at the edges it should just blur or deform the morph without any huge distortion.
Anyway, great job! Cannot wait to see how it actually works :D.

**Comment by ddowd97** [comment]
Yes to both! Either image can be modified in this manner and moving points affects the following morph as you would expect. The original gif I created to show that was too long so I went with this shorter one just showcasing the point translation instead... but the functionality is secretly there. ;)

Apologies for the delay, and thank you for your interest in this project once again. I'm _hoping_ I can push out a (hopefully) stable release in the coming weeks.

**Comment by jankaWIS** [comment]
Perfect! And no worries and no rush, I have also my project in such a stage for weeks :/, too many other things to do...
Good luck and I'm happy to "help" and comment.

**Comment by ddowd97** [comment]
I've finally bitten the bullet and released everything developed over the past few months as a v2.0 Beta update which you can find [here](https://github.com/ddowd97/Python-Image-Morpher/releases/tag/v2.0-beta)! This update includes the point moving/deleting behavior requested in this thread as well as a whole barrel of other features, changes, and fixes, so please let me know if you have any feedback. The intent of this beta update is to hopefully catch any severe bugs that come up (if any) for system configurations other than my own while I work on finalizing and integrating all of these new components together as time permits.

**Comment by ddowd97** [comment]
I am now releasing v2.0 as **Stable** as I have not received any issues/emails/etc. regarding the beta release from last month. As always, if you encounter any issues that have gone under my radar, please reach out and I will look into them as soon as possible. Best!
